<?php

namespace Domos\Core;

/**
 * This file is generated by the GenerateFeatureTypeEnumCommand.
 * The data it is generated from is in resources/data/feature-categories.json.
 * This JSON file is generated from the following Excel file:
 * 		Dropbox/05_domos/05_Marketingtool/Kategorie-Icons/Features.xlsx
 *
 * To regenerate, run: `php artisan features:generate`
 */
enum FeatureCategoryType: string
{
	case Architecture = 'architecture';
	case Basic = 'basic';
	case Custom = 'custom';
	case Ecology = 'ecology';
	case EnergyEfficiency = 'energy-efficiency';
	case Logistics = 'logistics';
	case Mobility = 'mobility';
	case SocialAffairs = 'social-affairs';
	case TechnicalBuildingEquipment = 'technical-building-equipment';

	public function label(?array $data = null): string
	{
		return match ($this) {
			static::Architecture => 'Architektur & Flächenstruktur',
			static::Basic => 'Allgemeine Fakten',
			static::Custom => 'Benutzerdefiniert',
			static::Ecology => 'Ökologie',
			static::EnergyEfficiency => 'Energieeffizienz',
			static::Logistics => 'Logistik & Produktion',
			static::Mobility => 'Mobilität',
			static::SocialAffairs => 'Soziales, Service & Sicherheit',
			static::TechnicalBuildingEquipment => 'Technische Gebäude Ausstattung',
		};
	}

	/**
	 * @return FeatureType[]
	 */
	public function features(): array
	{
		return match ($this) {
			static::Architecture => [
				FeatureType::AcousticCeiling,
				FeatureType::NumberOfRooms,
				FeatureType::NumberOfWorkplaces,
				FeatureType::Balcony,
				FeatureType::HandicapAccessible,
				FeatureType::HandicapFullyAccessible,
				FeatureType::Recepionist,
				FeatureType::FlooredWindows,
				FeatureType::RoofTerrace,
				FeatureType::DoubleFloor,
				FeatureType::Shower,
				FeatureType::WoodenFacade,
				FeatureType::HighCeilings,
				FeatureType::CeramicFacade,
				FeatureType::Kitchen,
				FeatureType::MeetingRooms,
				FeatureType::OpenRooms,
				FeatureType::HardwoodFlooring,
				FeatureType::RepresentativeFoyer,
				FeatureType::ServerRoom,
				FeatureType::TeeKitchen,
				FeatureType::CarpetFlooring,
				FeatureType::ThinkTanks,
				FeatureType::VariableRoomDivision,
				FeatureType::AccessControl,
			],
			static::Basic => [
				FeatureType::Address,
				FeatureType::YearOfConstruction,
				FeatureType::MonumentProtection,
				FeatureType::Floors,
				FeatureType::RentableArea,
				FeatureType::PlotArea,
				FeatureType::IndividuallyExpandable,
				FeatureType::CompletelyRenovated,
				FeatureType::Modernized,
				FeatureType::NewConstruction,
				FeatureType::YearOfRenovation,
				FeatureType::NeedsRenovation,
				FeatureType::Revitalized,
				FeatureType::MarketingWebsite,
			],
			static::Custom => [
				FeatureType::Custom,
			],
			static::Ecology => [
				FeatureType::GreenedRoof,
				FeatureType::GreenedFacade,
				FeatureType::Bees,
				FeatureType::GreenLeaseContracts,
				FeatureType::GreenCourtyard,
				FeatureType::WoodHybridConstruction,
				FeatureType::NearWater,
				FeatureType::MaximumSurfaceDesealing,
				FeatureType::NestingBox,
				FeatureType::Recycling,
				FeatureType::WaterRetention,
				FeatureType::UrbanGardening,
				FeatureType::WildFlowerGrasses,
			],
			static::EnergyEfficiency => [
				FeatureType::LightingWithMotionDetection,
				FeatureType::BlockHeating,
				FeatureType::ElectricHeating,
				FeatureType::DistrictHeating,
				FeatureType::GasHeating,
				FeatureType::GeoThermal,
				FeatureType::LedLighting,
				FeatureType::EcoEnergy,
				FeatureType::SolarEnergy,
				FeatureType::SmartMetering,
				FeatureType::SolarHeating,
				FeatureType::HeatPump,
				FeatureType::WindEnergy,
			],
			static::Logistics => [
				FeatureType::DeliveryFor24Hours,
				FeatureType::HeatedHalls,
				FeatureType::GroundLevelAccess,
				FeatureType::CooledHalls,
				FeatureType::StorageRack,
				FeatureType::MaxFloorLoad,
				FeatureType::HydraulicLift,
				FeatureType::InfraredHeating,
				FeatureType::HeavyDutyElevator,
				FeatureType::RampAccess,
				FeatureType::HeavyDutyCrane,
				FeatureType::RollingGates,
				FeatureType::HighVoltageOutlet,
				FeatureType::DressingRoom,
			],
			static::Mobility => [
				FeatureType::BikeSharing,
				FeatureType::Carsharing,
				FeatureType::DistanceAirport,
				FeatureType::DistancePort,
				FeatureType::DistanceMainStation,
				FeatureType::ElectricVehicleChargingStation,
				FeatureType::BikeSlots,
				FeatureType::LKWSlots,
				FeatureType::CloseToPublicTransport,
				FeatureType::ParkingGarage,
				FeatureType::PKWSlots,
			],
			static::SocialAffairs => [
				FeatureType::CentralFireAlarmSystem,
				FeatureType::CentralFireAlarmSystemFireDepartment,
				FeatureType::GastronomyOnSite,
				FeatureType::FiberglassConnection,
				FeatureType::Janitor,
				FeatureType::Cantina,
				FeatureType::Kindergarden,
				FeatureType::PlacesForSocializing,
				FeatureType::Guarded,
				FeatureType::CleaningService,
				FeatureType::SocialTenant,
				FeatureType::NearbySports,
				FeatureType::WashingClothes,
				FeatureType::CCTV,
			],
			static::TechnicalBuildingEquipment => [
				FeatureType::WiredWithCat7,
				FeatureType::OutdoorSunshadeElectric,
				FeatureType::ElectronicLock,
				FeatureType::StoreyHeating,
				FeatureType::FloorHeating,
				FeatureType::AirConditioning,
				FeatureType::Cooling,
				FeatureType::Ventilation,
				FeatureType::Elevators,
				FeatureType::LaboratoryS1,
				FeatureType::LaboratoryS2,
				FeatureType::OutdoorSunshade,
				FeatureType::SprinklerSystem,
				FeatureType::CentralHeating,
			],
		};
	}
}